openapi: "3.0.0"
info:
  version: 1.0.0
  title: twitterCloneApi
  description: Twitter Clone API
paths:
  /signup:
    post:
      description: userの新規登録
      operationId: signup
      requestBody:
        description: 登録するユーザーの情報
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"
      responses:
        "200":
          description: signup response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /login:
    post:
      description: userのログイン
      operationId: login
      requestBody:
        description: ログインするユーザーの情報
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"
      responses:
        "200":
          description: login response
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
                example:
                  token: example-token
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    user:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        password:
          type: string
      required:
        - name
        - password
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string