openapi: "3.0.0"
info:
  version: 1.0.0
  title: twitterCloneApi
  description: Twitter Clone API
security:
  - Bearer: []
paths:
  /signup:
    post:
      description: userの新規登録
      operationId: signup
      security: []
      requestBody:
        description: 登録するユーザーの情報
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"
      responses:
        "200":
          description: signup response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /login:
    post:
      description: userのログイン
      operationId: login
      security: []
      requestBody:
        description: ログインするユーザーの情報
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"
      responses:
        "200":
          description: login response
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
                example:
                  token: example-token
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/tweet:
    post:
      description: tweetを投稿
      operationId: createTweet
      requestBody:
        description: 投稿するtweetの内容
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tweet"
      responses:
        "200":
          description: login response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    user:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          minLength: 1
          maxLength: 20
        password:
          type: string
          minLength: 8
          maxLength: 20
      required:
        - name
        - password
    tweet:
      type: object
      properties:
        id:
          type: string
        text:
          type: string
          minLength: 1
          maxLength: 140
        user_id:
          type: string
        created_at:
          type: string
          format: date-time
      required:
        - text
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string